const defaultCats=[['tops','Tops','#dcf4e6'],['bottoms','Broeken en rokken','#d9ecff'],['dresses','Jurken','#ffe1e9'],['jackets','Jassen','#fff0c9'],['shoes','Schoenen','#eadfff'],['bags','Tassen','#f1dfd2'],['accessories','Accessoires','#e8f0ff']];
let data={},selected={tops:null,bottoms:null,shoes:null,bags:null},db;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('kleerkast_v11_db',1);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('state'))d.createObjectStore('state',{keyPath:'key'})};r.onsuccess=e=>res(e.target.result);r.onerror=e=>rej(e)})}
function getState(){return new Promise(res=>{const r=db.transaction('state','readonly').objectStore('state').get('app');r.onsuccess=()=>res(r.result?r.result.value:null);r.onerror=()=>res(null)})}
function setState(){return new Promise((res,rej)=>{const r=db.transaction('state','readwrite').objectStore('state').put({key:'app',value:data});r.onsuccess=()=>res(true);r.onerror=()=>rej(r.error)})}
async function save(){try{await setState();return true}catch(e){alert('Opslaan lukte niet.');return false}}
function initData(loaded){data=loaded||{};if(!data.categories)data.categories=defaultCats.map(c=>({id:c[0],name:c[1],color:c[2]}));data.categories.forEach(c=>{if(!data[c.id])data[c.id]=[]});if(!data.wishitems)data.wishitems=[];if(!data.outfits)data.outfits=[]}
function resizeImage(file,maxSize=900,quality=.7){return new Promise((res,rej)=>{const reader=new FileReader();reader.onerror=rej;reader.onload=e=>{const img=new Image();img.onerror=rej;img.onload=()=>{let w=img.width,h=img.height,s=Math.min(1,maxSize/Math.max(w,h));w=Math.round(w*s);h=Math.round(h*s);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);res(c.toDataURL('image/jpeg',quality))};img.src=e.target.result};reader.readAsDataURL(file)})}
function show(screen){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(screen).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===screen));scrollTo(0,0);render()}
function pick(cat){const i=document.getElementById('file-'+cat);if(i)i.click()}
async function handleFile(cat,file){if(!file)return;try{const src=await resizeImage(file);data[cat].push({id:Date.now()+Math.random(),src});await save();render()}catch(e){alert('Foto toevoegen lukte niet.')}}
async function removeItem(cat,id){const used=data.outfits.filter(o=>Object.values(o.items).includes(id));if(used.length&&!confirm('Dit kledingstuk zit in '+used.length+' outfit(s). Toch verwijderen?'))return;data[cat]=data[cat].filter(x=>x.id!==id);Object.keys(selected).forEach(k=>{if(selected[k]===id)selected[k]=null});await save();render()}
function select(cat,id,src,el){if(!(cat in selected))return;selected[cat]=id;document.getElementById('stack-'+cat).innerHTML='<img src="'+src+'">';document.querySelectorAll('[data-catrow="'+cat+'"] .piece').forEach(p=>p.classList.remove('active'));if(el)el.classList.add('active')}
function clearSlots(){selected={tops:null,bottoms:null,shoes:null,bags:null};const labels={tops:'Top',bottoms:'Onderstuk',shoes:'Schoenen',bags:'Tas'};Object.keys(labels).forEach(c=>document.getElementById('stack-'+c).textContent=labels[c]);document.querySelectorAll('.piece.active').forEach(p=>p.classList.remove('active'))}
async function saveOutfit(){if(!Object.values(selected).some(Boolean)){alert('Kies eerst minstens één kledingstuk.');return}data.outfits.push({id:Date.now(),date:new Date().toLocaleDateString('nl-BE'),items:{...selected}});await save();alert('Outfit bewaard');render()}
function findImg(id){for(const c of data.categories)for(const item of data[c.id])if(item.id===id)return item.src;return null}
function card(cat,item,selectable){const d=document.createElement('div');d.className='piece';const img=document.createElement('img');img.src=item.src;d.appendChild(img);if(selectable)img.onclick=()=>select(cat,item.id,item.src,d);const x=document.createElement('button');x.className='delete';x.textContent='Verwijder';x.onclick=e=>{e.stopPropagation();removeItem(cat,item.id)};d.appendChild(x);return d}
function row(cat,selectable){const r=document.createElement('div');r.className='row';r.dataset.catrow=cat;if(!data[cat]?.length){const e=document.createElement('div');e.className='empty';e.textContent='Nog geen foto’s';r.appendChild(e)}else data[cat].forEach(i=>r.appendChild(card(cat,i,selectable)));return r}
function render(){renderCloset();renderOutfitRows();renderCategories();renderWish();renderSaved();renderRecent()}
function renderCloset(){const cl=document.getElementById('closetList');cl.innerHTML='';data.categories.forEach(c=>{const s=document.createElement('div');s.className='section';s.innerHTML='<h2>'+c.name+'</h2>';const b=document.createElement('button');b.className='btn';b.textContent='Foto toevoegen';b.onclick=()=>pick(c.id);s.appendChild(b);cl.appendChild(s);const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.id='file-'+c.id;inp.onchange=e=>{handleFile(c.id,e.target.files[0]);e.target.value=''};cl.appendChild(inp);cl.appendChild(row(c.id,false))})}
function renderOutfitRows(){const out=document.getElementById('outfitRows');out.innerHTML='';['tops','bottoms','shoes','bags'].forEach(id=>{const c=data.categories.find(x=>x.id===id);if(!c)return;const s=document.createElement('div');s.className='section';s.innerHTML='<h2>'+c.name+'</h2>';out.appendChild(s);out.appendChild(row(id,true))})}
function renderCategories(){const list=document.getElementById('categoryList');list.innerHTML='';data.categories.forEach((c,idx)=>{const div=document.createElement('div');div.className='catrow';const left=document.createElement('div');left.className='catleft';left.innerHTML='<div class="dot" style="background:'+c.color+'"></div>'+c.name;const actions=document.createElement('div');actions.className='cat-actions';[['Naam',()=>renameCategory(c.id)],['↑',()=>moveCategory(idx,-1)],['↓',()=>moveCategory(idx,1)],['Verwijder',()=>deleteCategory(c.id)]].forEach(a=>{const b=document.createElement('button');b.className='mini';b.textContent=a[0];b.onclick=a[1];actions.appendChild(b)});div.append(left,actions);list.appendChild(div)})}
async function renameCategory(id){const c=data.categories.find(x=>x.id===id),name=prompt('Nieuwe naam?',c.name);if(!name)return;c.name=name;await save();render()}
async function moveCategory(i,dir){let n=i+dir;if(n<0||n>=data.categories.length)return;[data.categories[i],data.categories[n]]=[data.categories[n],data.categories[i]];await save();render()}
async function deleteCategory(id){if((data[id]||[]).length&&!confirm('Deze categorie bevat foto’s. Toch verwijderen?'))return;data.categories=data.categories.filter(x=>x.id!==id);delete data[id];await save();render()}
function renderWish(){const w=document.getElementById('wishRow');w.innerHTML='';if(!data.wishitems.length){const e=document.createElement('div');e.className='empty';e.textContent='Nog geen foto’s';w.appendChild(e)}else data.wishitems.forEach(i=>w.appendChild(card('wishitems',i,false)))}
function renderSaved(){const s=document.getElementById('savedList');s.innerHTML='';if(!data.outfits.length){const e=document.createElement('div');e.className='empty';e.textContent='Nog geen outfits bewaard';s.appendChild(e)}else data.outfits.forEach((o,i)=>{const box=document.createElement('div');box.className='panel';box.innerHTML='<h2>Outfit '+(i+1)+'</h2><p>Bewaard op '+o.date+'</p>';const rr=document.createElement('div');rr.className='row compact';Object.values(o.items).forEach(id=>{const src=findImg(id);if(src){const it=document.createElement('div');it.className='piece active';it.innerHTML='<img src="'+src+'">';rr.appendChild(it)}});box.appendChild(rr);s.appendChild(box)})}
function renderRecent(){const r=document.getElementById('recentRow');r.innerHTML='';const imgs=[];data.outfits.slice(-4).forEach(o=>Object.values(o.items).forEach(id=>{const src=findImg(id);if(src)imgs.push(src)}));if(!imgs.length)['Werk outfit','Weekend','Date night','Zondag casual'].forEach(t=>{const e=document.createElement('div');e.className='empty';e.style.minWidth='220px';e.textContent=t;r.appendChild(e)});else imgs.slice(0,4).forEach(src=>{const it=document.createElement('div');it.className='piece active';it.innerHTML='<img src="'+src+'">';r.appendChild(it)})}
async function addCategory(){const name=prompt('Naam van nieuwe categorie?');if(!name)return;const id='cat_'+Date.now(),colors=['#d9ecff','#dcf4e6','#ffe1e9','#fff0c9','#eadfff','#f1dfd2'];data.categories.push({id,name,color:colors[data.categories.length%colors.length]});data[id]=[];await save();render()}
async function init(){db=await openDB();initData(await getState());document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));document.getElementById('settingsBtn').onclick=()=>show('settings');document.getElementById('toggleAssistant').onclick=function(){document.getElementById('assistantBox').classList.toggle('collapsed');this.textContent=document.getElementById('assistantBox').classList.contains('collapsed')?'⌄':'⌃'};document.getElementById('saveOutfitBtn').onclick=saveOutfit;document.getElementById('clearBtn').onclick=clearSlots;document.getElementById('wishBtn').onclick=()=>pick('wishitems');document.getElementById('addCategoryBtn').onclick=addCategory;document.getElementById('addCategoryFromClosetBtn').onclick=addCategory;render()}
init();